<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="lijiaxiongdeMacBook-Air.local" ignored="0" name="~/Documents/project/TestNG" tests="5" failures="1" timestamp="29 Dec 2018 03:54:11 GMT" time="0.292" errors="0">
  <testcase name="failTest1" time="0.071" classname="testfail.TestFailRetry"/>
  <testcase name="failTest2" time="0.006" classname="testfail.TestFailRetry">
    <skipped/>
  </testcase> <!-- failTest2 -->
  <testcase name="failTest2" time="0.001" classname="testfail.TestFailRetry">
    <skipped/>
  </testcase> <!-- failTest2 -->
  <testcase name="failTest2" time="0.002" classname="testfail.TestFailRetry">
    <skipped/>
  </testcase> <!-- failTest2 -->
  <testcase name="failTest2" time="0.002" classname="testfail.TestFailRetry">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at testfail.TestFailRetry.failTest2(TestFailRetry.java:29)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- failTest2 -->
</testsuite> <!-- ~/Documents/project/TestNG -->
